language: csharp
solution: Servinte.Framework.Clinic.BasicInformation.sln
dist: trusty
sudo: required
mono: none
dotnet: 2.1.403
script:
- dotnet restore -s https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json -s https://api.nuget.org/v3/index.json
- dotnet build
